## Name: Tianze Ren (tr2bx) (Partner: TuNhi Vo (nt6jq))
#This is snowman with blue sky background, and there is a red sun in the top right corner.
import turtle

win = turtle.Screen()
win.setup(600, 600)

turtle.pen(speed=10)
turtle.penup()
turtle.goto(-300,300)
turtle.pendown()
turtle.pencolor('light blue')
turtle.fillcolor('light blue')
turtle.begin_fill()
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(600)
turtle.right(90)
turtle.forward(400)
turtle.end_fill()

turtle.pencolor('black')
turtle.fillcolor('white')
turtle.begin_fill()
turtle.penup()
turtle.goto(0, -75)
turtle.setheading(180)
turtle.pendown()
turtle.circle(90)
turtle.setheading(0)
turtle.circle(70)
turtle.end_fill()
turtle.circle(70,180)
turtle.begin_fill()
turtle.setheading(0)
turtle.circle(50)
turtle.end_fill()
turtle.penup()
turtle.goto(230,230)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
turtle.done()
