player = input("What player you would like to calculate statistic for?: ")
opponent = input("Against what opponent you would like to calculate their statistic for?: ")
attempted3 = input("How many 3's the player attempted?: ")
attempted3 = int(attempted3)
made3 = input("How many 3's the player made?: ")
made3 = int(made3)
attempted2 = input("How many 2's the player attempted?: ")
attempted2 = int(attempted2)
made2 = input("How many 2's the player made?: ")
made2 = int(made2)
attempted1 = input("How many free throws the player attempted?: ")
attempted1 = int(attempted1)
made1 = input("How many free throws the player made?: ")
made1 = int(made1)
field_goal_percentage = 100* ((made3 + made2) / (attempted3 + attempted2))
free_throw_percentage = 100* (made1 / attempted1)
total_number = made3*3 + made2*2 + made1
print(player, "had a " + str(field_goal_percentage) + "% field goal percentage and a", str(free_throw_percentage) + "% free throw percentage")
print(player + " scored" , str(total_number), "points against", opponent+". Wahoowa!")

